[tool.poetry]
name = "pycapsule"
version = "0.0.8"
description = "Various tools for Capsule BCI system"
authors = [
    "Yaroslav Shmelev <ysh@impulse-machine.com>"
]

[tool.poetry.dependencies]
python = "^3.7"
msgpack = "^1.0.0"
numpy= "^1.18.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
