[tool.poetry]
name = "simpleurdf"
version = "0.1.112"
description = "hello world"
authors = ["Bracewind <greg.pichereau@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.6.3"
PyXB = "^1.2.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["simpleurdf", "simpleurdf_model_example", "tests"]
exclude=["simpleurdf/scripts", "simpleurdf/createpackage"]