[tool.poetry]
name = "cesp"
version = "1.5.1"
description = "Converts blank space to underscore and other characters to avoid problems"
authors = ["Marcus Bruno Fernandes Silva <marcusbfs@gmail.com>"]
license = "MIT"
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.7"
rich = "^10.2.0"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
mypy = "^0.812"
isort = "^5.8.0"
autoflake = "^1.4"
py7zr = "^0.16.1"
pyinstaller = "^4.3"

[tool.poetry.scripts]
cesp = "cesp:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
