[tool.poetry]
name = "secondstate"
version = "1.0.2"
description = ""
authors = ["Lewis <lewis@fruiti.app>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.12.0"
pytest-monitor = "^1.6.0"
gprof2dot = "^2021.2.21"
black = "^21.5b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
