[tool.poetry]
name = "escape-py"
version = "1.0.0-beta.12"
description = "Escape's Python CLI"
authors = ["Escape Technologies SAS <ping@escape.tech>"]
maintainers = ["Antoine Carossio <antoine.carossio@me.com>", "Maxence Lecanu <lecanu.maxence@gmail.com>"]
license = "Proprietary"
packages = [
    { include = "escape_cli" }
]
include = [
    "LICENSE",
]
readme = "README.md"
"homepage" = "https://escape.tech/"
"repository" = "https://gitlab.com/escape.tech/product"

[tool.poetry.urls]
"Bug Tracker" = "https://gitlab.com/escape.tech/product/issues"

[tool.poetry.scripts]
escape-py = 'escape_cli:main'

[tool.poetry.dependencies]
python     = "^3.9"
click      = "^7.1.2"
loguru     = "^0.5.3"
inquirer   = "^2.7.0"
requests   = "^2.25.1"
simplejson = "^3.17.2"
coverage   = "^5.5"
Django = "^3.2"
Flask = "^1.1.2"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
setuptools = "^45"
pylint = "^2.7.4"
yapf = "^0.31.0"
pylint-quotes = "^0.2.1"
mypy = "^0.812"
docformatter = "^1.4"
unify = "^0.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "escape_cli/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
hvcs = "gitlab"
upload_to_pypi = true
upload_to_release = true
build_command = "pip3 install poetry && poetry build"
