[tool.poetry]
name = "syneto_api"
version = "0.2.21"
description = "Syneto Client API library"
authors = ["Your Name <you@example.com>"]
license = "Proprietary"
homepage = "https://github.com/SynetoNet/syneto-api"
repository = "https://github.com/SynetoNet/syneto-api"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
python-dotenv = "^0.16"
requests = {extras = ["secure"], version = "^2.25"}
inflection = "^0.5"
aiohttp = {version = "^3.7", extras = ["speedups"]}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
ipdb = "^0.13.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
