[tool.poetry]
name = "gallica-autobib"
version = "0.1.6"
description = "Automatically match Bibliographies against bnf.gallica.fr"
authors = ["John Morris <2e0byo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.5.1"
sruthi = "^0.1.2"
fuzzywuzzy = "^0.18.0"
python-Levenshtein = "^0.12.2"
xmltodict = "^0.12.0"
beautifulsoup4 = "^4.9.3"
rfc3987 = "^1.3.8"
lark-parser = "^0.11.3"
lxml = "^4.6.3"
bibtexparser = "^1.2.0"
rispy = "^0.6.0"
roman = "^3.3"
Pillow = "^8.2.0"
PyPDF4 = "^1.27.0"
requests-downloader = "^0.1.6"
scikit-image = "^0.18.1"
typer = "^0.3.2"
Jinja2 = "^2.11.3"
python-slugify = "^5.0.2"
fuzzysearch = "^0.7.3"
xdg = "^5.0.2"
sqlitedict = "^1.7.0"
jsonpickle = "^2.0.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.0.5"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pre-commit = "^2.4.0"
pytest = "^6.0.1"
mkdocs = "^1.1"
mkdocs-material = "^6.0.1"
markdown-include = "^0.6.0"
pytest-sugar = "^0.9.4"
pytest-cov = "^2.11.1"
pytest-coverage = "^0.0"
devtools = "^0.6.1"
pytest-regressions = "^2.2.0"
deepdiff = "^5.5.0"
pytest-diff = "^0.1.14"
numpy = "^1.20.2"
importmagic = "^0.1.7"
diff-pdf-visually = "^1.6.2"
mypy = "^0.812"
pytest-asyncio = "^0.15.1"
mkdocs-versioning = "^0.4.0"
pytest-mock = "^3.6.1"
matplotlib = "^3.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.plugins."console_scripts"]
gallica-autobib = "gallica_autobib.cli:app"